### ISSUE TITLE
Some files can't have multiple locales at the same time

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GTNH-Translations#8]
I tried unzipping all the locale releases, and i got some file conflicts. So this makes it impossible for now to ship the locales in nightlies nor stable releases. Here is the list of files that needs to be dealt with:
- [x] `./config/CustomMainMenu/*`
- [x] `./config/InGameInfoXML`
- [x] `./config/GTNewHorizons/CustomToolTips.xml`

**Comment by boubou19** [comment]
So we have a fork of https://github.com/GTNewHorizons/Custom-Main-Menu and https://github.com/GTNewHorizons/InGame-Info-XML so at least we don't face ARR mods

**Comment by IcaroKaue** [comment]
This is low priority, but iirc there is also craftpresence.json. That might mess things up.

**Comment by IcaroKaue** [comment]
Also, there are the mods which are currently unsupported:

- [ ] IC2 - Uses a different file called "xx_XX.properties" at [IC2].jar/ic2/lang/. (Note: this already has a translation, however it appears to be inconsistent and incomplete in many cases.)
- [ ] BetterLoadingScreen - Though there is a xx_XX.lang in the txloader folder for it, it does not appear to be translated. Perhaps it does not load quick enough?

Please comment if there are any mods I missed.

**Comment by miozune** [comment]
> * [ ]  BetterLoadingScreen - Though there is a xx_XX.lang in the txloader folder for it, it does not appear to be translated. Perhaps it does not load quick enough?

Are you talking about https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/tree/master/config/txloader/forceload/betterloadingscreen/textures/backgrounds or https://github.com/GTNewHorizons/GTNH-Translations/blob/master/pt_BR/config/Betterloadingscreen/tips/pt_BR.txt?

**Comment by IcaroKaue** [comment]
> > * [ ]   BetterLoadingScreen - Though there is a xx_XX.lang in the txloader folder for it, it does not appear to be translated. Perhaps it does not load quick enough?
> 
> Are you talking about https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/tree/master/config/txloader/forceload/betterloadingscreen/textures/backgrounds or https://github.com/GTNewHorizons/GTNH-Translations/blob/master/pt_BR/config/Betterloadingscreen/tips/pt_BR.txt?

https://github.com/GTNewHorizons/GTNH-Translations/blob/master/pt_BR/config/txloader/forceload/Better%20Loading%20Screen%20GTNH%5Bbetterloadingscreen%5D/lang/pt_BR.lang

**Comment by miozune** [comment]
So it turns out that BLS has its own translation loader, just for translating "Minecraft Initialization" where lang resources are not loaded yet. Maybe we can place translation back to mod jar and call it a day.

**Comment by miozune** [comment]
Closing as the original goal has been achieved. @IcaroKaue If you want to ship translated `craftpresence.json` with the modpack, please contact the dev of CraftPresence
